spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Don't enable ddl-auto for production
    show-sql: true
